### ISSUE TITLE
Request permission for code re-use

### ISSUE THREAD

**Issue by gouttegd** [monarch-ebi-dev/eqwriter#2]
The `eqwriter` is used by FlyBase ontologies to (1) automatically generate definitions for logically defined classes whose existing definition is simply `.` (so-called “dot definitions”) and (2) automatically “import” definitions from external classes, for classes whose existing definition is of the form `$sub_ABC:1234` (so-called “sub definitions”).

There are issues with the way this works. For example, if the foreign term referred by a “sub definition” does not itself have a definition, the tool generates a default definition of “No description.” – it would be better to remove the definition entirely in that case rather than to generate a useless one (if only to avoid “duplicate definitions” in ROBOT reports).

Rather than fixing the issues in here though, I’d like to re-implement those features as ROBOT plugins, for the sake of efficiency. But the code here has no license, so I hereby request permission to re-use it (any re-implementation would itself be published under a free/libre license).

**Comment by gouttegd** [comment]
@matentzn The request should presumably go to you as you seemed to have written all of it – unless the code belongs to the EBI?

**Comment by matentzn** [comment]
Take all the code and do with it as you see fit. Consider this comment a permission by the author to copy the code without attribution or anything!

**Comment by gouttegd** [comment]
New ROBOT plugin is here: https://github.com/FlyBase/flybase-robot-plugin
